-- Seeding Exercises with English categories and multi-part support

INSERT INTO exercises (name, body_parts, type, user_id) VALUES
-- Chest
('Barbell Bench Press', ARRAY['Chest', 'Triceps'], 'barbell', NULL),
('Dumbbell Bench Press', ARRAY['Chest'], 'dumbbell', NULL),
('Incline Barbell Press', ARRAY['Chest', 'Shoulders (Front)'], 'barbell', NULL),
('Decline Press', ARRAY['Chest'], 'barbell', NULL),
('Chest Press Machine', ARRAY['Chest'], 'machine', NULL),
('Smith Machine Press', ARRAY['Chest'], 'machine', NULL),
('Svend Press', ARRAY['Chest'], 'dumbbell', NULL),
('Reverse Grip Bench Press', ARRAY['Chest', 'Triceps'], 'barbell', NULL),
('Wide Grip Bench Press', ARRAY['Chest'], 'barbell', NULL),
('Dumbbell Floor Press', ARRAY['Chest', 'Triceps'], 'dumbbell', NULL),
('Dumbbell Flyes', ARRAY['Chest'], 'dumbbell', NULL),
('Cable Flyes', ARRAY['Chest'], 'cable', NULL),
('Pec Deck', ARRAY['Chest'], 'machine', NULL),
('Push-ups', ARRAY['Chest', 'Triceps', 'Core'], 'bodyweight', NULL),
('Chest Dips', ARRAY['Chest', 'Triceps'], 'bodyweight', NULL),

-- Back
('Pull-up', ARRAY['Back (Lats)'], 'bodyweight', NULL),
('Chin-up', ARRAY['Back (Lats)', 'Biceps'], 'bodyweight', NULL),
('Wide Grip Lat Pulldown', ARRAY['Back (Lats)'], 'machine', NULL),
('Bent Over Barbell Row', ARRAY['Back (Lats)', 'Back (Upper/Traps)', 'Lower Back'], 'barbell', NULL),
('One Arm Dumbbell Row', ARRAY['Back (Lats)', 'Back (Upper/Traps)'], 'dumbbell', NULL),
('T-Bar Row', ARRAY['Back (Lats)', 'Back (Upper/Traps)'], 'machine', NULL),
('Seated Cable Row', ARRAY['Back (Lats)', 'Back (Upper/Traps)'], 'cable', NULL),
('Chest Supported Row', ARRAY['Back (Upper/Traps)'], 'machine', NULL),
('Meadows Row', ARRAY['Back (Lats)', 'Shoulders (Rear)'], 'barbell', NULL),
('Inverted Row', ARRAY['Back (Upper/Traps)', 'Core'], 'bodyweight', NULL),
('Rack Pull', ARRAY['Back (Upper/Traps)', 'Lower Back'], 'barbell', NULL),
('Face Pull', ARRAY['Shoulders (Rear)', 'Back (Upper/Traps)'], 'cable', NULL),
('Barbell Shrugs', ARRAY['Back (Upper/Traps)'], 'barbell', NULL),
('Back Extension', ARRAY['Lower Back', 'Glutes'], 'bodyweight', NULL),
('Dumbbell Pullover', ARRAY['Back (Lats)', 'Chest'], 'dumbbell', NULL),
('Straight Arm Pulldown', ARRAY['Back (Lats)'], 'cable', NULL),
('Deadlift (Conventional)', ARRAY['Lower Back', 'Glutes', 'Hamstrings', 'Back (Upper/Traps)'], 'barbell', NULL),

-- Shoulders
('Military Press', ARRAY['Shoulders (Front)', 'Triceps'], 'barbell', NULL),
('Seated Dumbbell Press', ARRAY['Shoulders (Front)'], 'dumbbell', NULL),
('Arnold Press', ARRAY['Shoulders (Front)', 'Shoulders (Side)'], 'dumbbell', NULL),
('Dumbbell Lateral Raise', ARRAY['Shoulders (Side)'], 'dumbbell', NULL),
('Cable Lateral Raise', ARRAY['Shoulders (Side)'], 'cable', NULL),
('Upright Row', ARRAY['Shoulders (Side)', 'Back (Upper/Traps)'], 'barbell', NULL),
('Dumbbell Front Raise', ARRAY['Shoulders (Front)'], 'dumbbell', NULL),
('Rear Delt Fly', ARRAY['Shoulders (Rear)'], 'dumbbell', NULL),
('Handstand Push-up', ARRAY['Shoulders (Front)', 'Triceps'], 'bodyweight', NULL),
('Push Press', ARRAY['Shoulders (Front)', 'Quadriceps'], 'barbell', NULL),
('Landmine Press', ARRAY['Shoulders (Front)', 'Chest'], 'barbell', NULL),
('Cuban Press', ARRAY['Shoulders (Side)', 'Back (Upper/Traps)'], 'barbell', NULL),

-- Legs (Ant)
('Back Squat (High Bar)', ARRAY['Quadriceps', 'Glutes'], 'barbell', NULL),
('Back Squat (Low Bar)', ARRAY['Glutes', 'Quadriceps', 'Lower Back'], 'barbell', NULL),
('Front Squat', ARRAY['Quadriceps', 'Core'], 'barbell', NULL),
('Leg Press', ARRAY['Quadriceps', 'Glutes'], 'machine', NULL),
('Hack Squat', ARRAY['Quadriceps'], 'machine', NULL),
('Leg Extension', ARRAY['Quadriceps'], 'machine', NULL),
('Bulgarian Split Squat', ARRAY['Quadriceps', 'Glutes'], 'dumbbell', NULL),
('Walking Lunges', ARRAY['Quadriceps', 'Glutes'], 'dumbbell', NULL),
('Step-up', ARRAY['Quadriceps', 'Glutes'], 'dumbbell', NULL),
('Sissy Squat', ARRAY['Quadriceps'], 'bodyweight', NULL),
('Pistol Squat', ARRAY['Quadriceps', 'Glutes'], 'bodyweight', NULL),
('Goblet Squat', ARRAY['Quadriceps', 'Glutes'], 'dumbbell', NULL),

-- Legs (Post)
('Romanian Deadlift', ARRAY['Hamstrings', 'Glutes', 'Lower Back'], 'barbell', NULL),
('Sumo Deadlift', ARRAY['Glutes', 'Quadriceps', 'Hamstrings'], 'barbell', NULL),
('Hip Thrust', ARRAY['Glutes'], 'barbell', NULL),
('Glute Bridge', ARRAY['Glutes'], 'bodyweight', NULL),
('Kettlebell Swing', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], 'dumbbell', NULL),
('Good Morning', ARRAY['Hamstrings', 'Lower Back'], 'barbell', NULL),
('Seated Leg Curl', ARRAY['Hamstrings'], 'machine', NULL),
('Lying Leg Curl', ARRAY['Hamstrings'], 'machine', NULL),
('Glute-Ham Raise', ARRAY['Hamstrings', 'Glutes'], 'bodyweight', NULL),
('Cable Pull-Through', ARRAY['Glutes', 'Hamstrings'], 'cable', NULL),
('Standing Calf Raise', ARRAY['Calves'], 'machine', NULL),
('Seated Calf Raise', ARRAY['Calves'], 'machine', NULL),
('Donkey Calf Raise', ARRAY['Calves'], 'machine', NULL),
('Clamshells', ARRAY['Glutes'], 'bodyweight', NULL),
('Hip Abduction Machine', ARRAY['Glutes'], 'machine', NULL),

-- Arms
('Barbell Curl', ARRAY['Biceps'], 'barbell', NULL),
('Dumbbell Hammer Curl', ARRAY['Biceps', 'Forearms'], 'dumbbell', NULL),
('Preacher Curl', ARRAY['Biceps'], 'barbell', NULL),
('Incline Dumbbell Curl', ARRAY['Biceps'], 'dumbbell', NULL),
('Concentration Curl', ARRAY['Biceps'], 'dumbbell', NULL),
('Skull Crushers', ARRAY['Triceps'], 'barbell', NULL),
('Tricep Pushdown', ARRAY['Triceps'], 'cable', NULL),
('Overhead Tricep Extension', ARRAY['Triceps'], 'dumbbell', NULL),
('Bench Dips', ARRAY['Triceps'], 'bodyweight', NULL),
('Close Grip Bench Press', ARRAY['Triceps', 'Chest'], 'barbell', NULL),
('Tricep Kickbacks', ARRAY['Triceps'], 'dumbbell', NULL),
('Wrist Curl', ARRAY['Forearms'], 'barbell', NULL),
('Reverse Wrist Curl', ARRAY['Forearms'], 'barbell', NULL),
('Farmers Carry', ARRAY['Forearms', 'Back (Upper/Traps)', 'Core'], 'dumbbell', NULL),
('Plate Pinch', ARRAY['Forearms'], 'dumbbell', NULL),

-- Core
('Plank', ARRAY['Core'], 'bodyweight', NULL),
('Ab Wheel Rollout', ARRAY['Core'], 'bodyweight', NULL),
('Hanging Leg Raise', ARRAY['Core'], 'bodyweight', NULL),
('Cable Crunch', ARRAY['Core'], 'cable', NULL),
('Russian Twist', ARRAY['Core'], 'bodyweight', NULL),
('Bicycle Crunch', ARRAY['Core'], 'bodyweight', NULL),
('Side Plank', ARRAY['Core'], 'bodyweight', NULL),
('Woodchopper', ARRAY['Core'], 'cable', NULL),
('Dead Bug', ARRAY['Core'], 'bodyweight', NULL),
('Vacuum', ARRAY['Core'], 'bodyweight', NULL),
('Dragon Flag', ARRAY['Core'], 'bodyweight', NULL),
('L-Sit', ARRAY['Core'], 'bodyweight', NULL),

-- Functional
('Box Jump', ARRAY['Functional', 'Quadriceps'], 'bodyweight', NULL),
('Burpee', ARRAY['Functional', 'Chest', 'Quadriceps'], 'bodyweight', NULL),
('Battle Ropes', ARRAY['Functional', 'Shoulders (Side)', 'Core'], 'cable', NULL),
('Prowler Sled Push', ARRAY['Functional', 'Quadriceps'], 'machine', NULL),
('Medicine Ball Slam', ARRAY['Functional', 'Core', 'Back (Lats)'], 'bodyweight', NULL),
('Jump Squat', ARRAY['Functional', 'Quadriceps'], 'bodyweight', NULL),
('Turkish Get-Up', ARRAY['Functional', 'Shoulders (Front)', 'Core'], 'dumbbell', NULL),
('Wall Ball Shot', ARRAY['Functional', 'Quadriceps', 'Shoulders (Front)'], 'bodyweight', NULL),
('Mountain Climber', ARRAY['Functional', 'Core'], 'bodyweight', NULL),
('Double Unders', ARRAY['Functional', 'Calves'], 'bodyweight', NULL),
('Broad Jump', ARRAY['Functional', 'Glutes', 'Quadriceps'], 'bodyweight', NULL),
('Tire Flip', ARRAY['Functional', 'Glutes', 'Lower Back'], 'bodyweight', NULL),
('Skater Hops', ARRAY['Functional', 'Glutes'], 'bodyweight', NULL),
('Muscle-up', ARRAY['Functional', 'Back (Lats)', 'Triceps'], 'bodyweight', NULL);